### ISSUE TITLE
Unnecessary package?

### ISSUE THREAD

**Issue by asr** [alejogm0520/latexEAFIT#1]
Running

```
$ cd Plantilla\ Beamer
$ pdflatex plantilla.tex
```

I got the error

```
! LaTeX Error: File `pgfplots.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
```

by pressing the ENTER key, it seems the `plantilla.pdf` file is generated without problems.

**Comment by alejogm0520** [comment]
@asr 
I removed the requirement of the pgfplots package. Could you check this again? 

I couldn't replicate this error, but I remove the line that ask for this package.

**Comment by asr** [comment]
Thanks!
