### ISSUE TITLE
Amumu?

### ISSUE THREAD

**Issue by asr** [alejogm0520/latexEAFIT#10]
The [release](https://github.com/alejogm0520/latexEAFIT/releases/tag/v3.3) was called `Amumu`? Was it on purpose?

**Comment by alejogm0520** [comment]
[Amumu](http://gameinfo.euw.leagueoflegends.com/en/game-info/champions/amumu/) is a character in my favorite videogame. I'm planning name each major release
with one of the [LoL](http://gameinfo.euw.leagueoflegends.com/en/game-info/get-started/what-is-lol/) characteres.

**Comment by asr** [comment]
I feel to grow up :-)
