### ISSUE TITLE
Update the template in Sharelatex

### ISSUE THREAD

**Issue by jonaprieto** [alejogm0520/latexEAFIT#11]
- [x]  update to latest version
- [ ]  thumbnail

And I suggest to change the name of the template:

> Inspire Create Transform - EAFIT

Maybe it can be:

> Universidad EAFIT Beamer

Many of the templates in Sharelatex are not official and I don't think so to mention
is unofficial.

**Comment by jonaprieto** [comment]
Did you solve it?

**Comment by alejogm0520** [comment]
"This is an template of Universidad EAFIT Beamer, based on the official PowerPoint Slides." Yes
