### ISSUE TITLE
Missing date information from the title page

### ISSUE THREAD

**Issue by asr** [alejogm0520/latexEAFIT#13]
The date information is missing from the title page when using the  `EAFIT` Beamer theme:

`test.tex`:

```latex
\documentclass[presentation]{beamer}

\usetheme[language=EN]{EAFIT}%
% \usetheme{default}%

% My title
\title[]{My Title}
\author{Author}
\date{February 13, 2018}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}

% First slide: Inspira Crea Transforma
\begin{frame}
\end{frame}

\begin{frame}
\titlepage
\end{frame}

\end{document}
```

Note that `February 13, 2018` is missing in the [test.pdf](https://github.com/alejogm0520/latexEAFIT/files/1720231/test.pdf) file. I have no this problem when using the default theme.

**Comment by alejogm0520** [comment]
@asr  Check the commit https://github.com/alejogm0520/latexEAFIT/commit/2b664c7dcb90baaaca137ff0a3ecfa249cb522f7?diff=unified 

Thanks

**Comment by asr** [comment]
Well, I can see the date now, but it isn't centred.

**Comment by alejogm0520** [comment]
@asr  Please check:
https://github.com/alejogm0520/latexEAFIT/commit/fdf6bb3fdeba92ea0cd6ebad9d5026165bcd35f3

**Comment by asr** [comment]
Using the default theme (and some themes from [here](http://deic.uab.es/~iblanes/beamer_gallery/index_by_theme.html)) the author and the date are both with/without bold face. Is there some reason the author is in bold face but the date isn't?

**Comment by alejogm0520** [comment]
@asr Could you confirm the official guidelines for the title page?

**Comment by asr** [comment]
Status: Waiting the templates from Paulina.

**Comment by asr** [comment]
After seeing the templates there are no any guidelines, so it's up to you. Thanks!
