### ISSUE TITLE
The titles of the blocks do not use boldface

### ISSUE THREAD

**Issue by asr** [alejogm0520/latexEAFIT#14]
The titles of the blocks do not use boldface when using the `EAFIT` Beamer theme.

**Comment by asr** [comment]
Any news on it?

**Comment by alejogm0520** [comment]
@asr  Please check:

https://github.com/alejogm0520/latexEAFIT/commit/dc0d1325f430fa95c25edcb505983e716de96d9d

**Comment by asr** [comment]
Thanks!
