### ISSUE TITLE
Acknowledge required?

### ISSUE THREAD

**Issue by BalmungSan** [alejogm0520/latexEAFIT#15]
Do I require some formal acknowledge for using this template for presentation inside the university?, and if that is the case what would be the correct format?

By the way, I will mention during the presentation the usage of this awesome template. I just want to know if there is a formal way for doing so.

 _PS: Thank you very much for this great work_

**Comment by alejogm0520** [comment]
_Do I require some formal acknowledge for using this template for presentation inside the university?, and if that is the case what would be the correct format?_

No. Just follow the template (cover page, title page, and don't change the color scheme).

_By the way, I will mention during the presentation the usage of this awesome template. I just want to know if there is a formal way for doing so._

Nah, just put the link :P Thanks for using and share  :)
