### ISSUE TITLE
Missing "Vigilada Mineducación"

### ISSUE THREAD

**Issue by asr** [alejogm0520/latexEAFIT#4]
EAFIT has the above information in your official slides.

**Comment by alejogm0520** [comment]
Thanks

**Comment by asr** [comment]
Did you fix the issue? Which was the commit?

**Comment by alejogm0520** [comment]
https://github.com/alejogm0520/latexEAFIT/commit/5cb7512da9876168a0862d233ef7429eff302220 This one
