### ISSUE TITLE
Unnecessary mandatory information on the title page

### ISSUE THREAD

**Issue by asr** [alejogm0520/latexEAFIT#5]
From the `template.tex` file:

```latex
% Se define la Escuela
\def\escuela{Escuela de Ciencias}
% Se define el Departamento
\def\departamento{Departamento de Ciencias Matemáticas}
% Se define la Carrera
\def\carrera{Maestria en Matemáticas Aplicadas}
```

The above definitions are not used by all the presentations but `\titlepage` always uses them. For example, if I wrote something like

```latex
\title{Grupo de Lógica y Computación}
\author{Andrés Sicard Ramírez}
\date{\today}
```

the .pdf has something like

```
Grupo de Lógica y Computación
Andrés Sicard Ramírez

Universidad EAFIT
Escuela
Departamento
Carrera
```

I suggest to remove these definitions.

**Comment by alejogm0520** [comment]
I change the default value:

\def\escuela{$ $}
\def\departamento{$  $}
\def\carrera{$  $}
For a empty one.

**Comment by asr** [comment]
Thanks!

**Comment by asr** [comment]
I see 'Universidad EAFIT' (which I didn't write) in the title page when using the template on [test.tex.txt](https://github.com/alejogm0520/latexEAFIT/files/916945/test.tex.txt).

**Comment by alejogm0520** [comment]
I add a new definition:
\def\eafit{$ $}
for the
\def\eafit{Universidad EAFIT}

**Comment by asr** [comment]
Thanks for fixing the issue.
