### ISSUE TITLE
Babel incompatibility

### ISSUE THREAD

**Issue by asr** [alejogm0520/latexEAFIT#7]
On the file [test.tex.txt](https://github.com/alejogm0520/latexEAFIT/files/917021/test.tex.txt), I got the following error when using Spanish/ES on both the template and the Babel package:

```
$ pdflatex test.tex

! LaTeX Error: Option clash for package babel.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.15 \def
         \beamer@EAFIT@fontc{none}
```

**Comment by alejogm0520** [comment]
Thanks.

I change the option "RequierePackage" depending of ES or EN.

**Comment by asr** [comment]
Thanks for fixing the issue.
